// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMTMrFoo13XXf_w2jxbDNzvbzYy6oNMIk',
    appId: '1:655761647141:web:d478408d7cdace183301cc',
    messagingSenderId: '655761647141',
    projectId: 'wazafk-29375',
    authDomain: 'wazafk-29375.firebaseapp.com',
    storageBucket: 'wazafk-29375.firebasestorage.app',
    measurementId: 'G-99GB538YS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJsMasv-k7DVxpoKInuaTKXfv9zkSRHTY',
    appId: '1:655761647141:android:12b379717d4fdb433301cc',
    messagingSenderId: '655761647141',
    projectId: 'wazafk-29375',
    storageBucket: 'wazafk-29375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYqxAcdrnpmZVpFouGJ4kpsAmeFPeR948',
    appId: '1:655761647141:ios:bfe931e22a6d20583301cc',
    messagingSenderId: '655761647141',
    projectId: 'wazafk-29375',
    storageBucket: 'wazafk-29375.firebasestorage.app',
    iosBundleId: 'com.wazafak.wazafk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYqxAcdrnpmZVpFouGJ4kpsAmeFPeR948',
    appId: '1:655761647141:ios:f857140c991850ee3301cc',
    messagingSenderId: '655761647141',
    projectId: 'wazafk-29375',
    storageBucket: 'wazafk-29375.firebasestorage.app',
    iosBundleId: 'com.wazafak.wazafakApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMTMrFoo13XXf_w2jxbDNzvbzYy6oNMIk',
    appId: '1:655761647141:web:cefec2d34e0ee05d3301cc',
    messagingSenderId: '655761647141',
    projectId: 'wazafk-29375',
    authDomain: 'wazafk-29375.firebaseapp.com',
    storageBucket: 'wazafk-29375.firebasestorage.app',
    measurementId: 'G-92TCR7G1N3',
  );
}
